[manager]

ratio = [0, 4, 6]
sort_dir_first = true
linemode = "none"
show_hidden = true
show_symlink = true
title_format = "{cwd}"

[preview]

wrap = "no"
tab_size = 4

[opener]

# edit = [
#   { run = 'nu ~/.dotfiles/config/.config/yazi/open_file.nu "$0"', desc = "Open File in a new window", block = true },
# ]
